import Head from "next/head";
import Releases from "@/components/releases";
import Releases2 from "@/components/releases/index2";
import Releases3 from "@/components/releases/index3";
import Releases4 from "@/components/releases/index4";
import Releases5 from "@/components/releases/index5";
import AnimationReleases12 from "@/components/AnimationReleases/index12";
import AnimationReleases11 from "@/components/AnimationReleases/index11";
import AnimationReleases10 from "@/components/AnimationReleases/index10";
import MMHoldingScreen from "@/components/UnderConstruction/index";
import MM_Hero from "@/components/mm_hero/index";
import MM_Hero2 from "@/components/mm_hero/index2";
import MMDiscosHero from "@/components/MMDiscos_Hero/MMDiscosHero";
import MM_Hero3 from "@/components/mm_hero/index3";
import MMDiscosHero2 from "@/components/MMDiscos_Hero/MMDiscosHero2";
import ParallaxGallery2 from "@/components/ParallaxGallery/ParallaxGallery2";
import AboutSection5 from "@/components/About/index5";
import MMDiscosHero3 from "@/components/MMDiscos_Hero/MMDiscosHero3";
import MMDiscosHero4 from "@/components/MMDiscos_Hero/MMDiscosHero4";
import MMDiscosHeroFinal from "@/components/MMDiscos_Hero/MMDiscosHeroFinal";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useLayoutEffect, useRef, useState, useEffect } from "react";
import Lenis from "lenis";
import MMDiscosHeroFinal2 from "@/components/MMDiscos_Hero/MMDiscosHeroFinal2";
import MMDiscosHeroFinal3 from "@/components/MMDiscos_Hero/MMDiscosHeroFinal3";
import MMDiscosHeroFinal4 from "@/components/MMDiscos_Hero/MMDiscosHeroFinal4";
import MMHeroMobileFinal from "@/components/MMDiscos_Hero/MMHeroMobileFinal";

gsap.registerPlugin(ScrollTrigger);

export default function Home() {

  const lenisRef = useRef(null);

  // Detecta si el dispositivo es móvil tras el mount (evita mismatch SSR)
  const [isMobile, setIsMobile] = useState(null);
  useEffect(() => {
    setIsMobile(window.innerWidth < 720);
  }, []);

  // useLayoutEffect: antes que los useEffect de los hijos (p. ej. MMHero), para que Lenis + proxy existan cuando se crean los ScrollTriggers
  useLayoutEffect(() => {
    history.scrollRestoration = "manual";
    window.scrollTo(0, 0);

    const lenis = new Lenis();
    lenisRef.current = lenis;
    lenis.scrollTo(0, { immediate: true });

    const scroller = document.documentElement;
    ScrollTrigger.scrollerProxy(scroller, {
      scrollTop(value) {
        if (arguments.length) {
          lenis.scrollTo(value, { immediate: true, force: true });
        }
        return lenis.scroll;
      },
      getBoundingClientRect() {
        return {
          top: 0,
          left: 0,
          width: window.innerWidth,
          height: window.innerHeight,
        };
      },
    });
    ScrollTrigger.defaults({ scroller });
    ScrollTrigger.refresh();

    lenis.on("scroll", ScrollTrigger.update);
    const rafCb = (time) => lenis.raf(time * 1000);
    gsap.ticker.add(rafCb);
    gsap.ticker.lagSmoothing(0);

    return () => {
      gsap.ticker.remove(rafCb);
      lenis.destroy();
      lenisRef.current = null;
      ScrollTrigger.scrollerProxy(scroller);
      delete ScrollTrigger.defaults().scroller;
      ScrollTrigger.refresh(true);
    };
  }, []);

  return (
    <div>
      {/* <Head>
        <title>MM Discos | Balearic Soundsystem</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      {/* Hero: mobile vs desktop */}
      {isMobile === null
        ? null                       // evita flash antes de detectar
        : isMobile
          ? <MMHeroMobileFinal />
          : <MMDiscosHeroFinal3 />
      }
      <ParallaxGallery2 />
      <AboutSection5 />
    </div>
  );
}
