import Head from "next/head";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useLayoutEffect, useRef, useState, useEffect } from "react";
import { useRouter } from "next/router";
import Lenis from "lenis";
import AboutFinal2 from "@/components/About/AboutFinal2";
import Highlights2Wrapper from "@/components/Highlights/Highlights2Wrapper";
import MMNewestHero2Wrapper from "@/components/MMDiscos_Hero/MMNewestHero2Wrapper";

gsap.registerPlugin(ScrollTrigger);

// Previene que la barra de direcciones del móvil dispare un resize
// que recalcule los puntos de ScrollTrigger mid-scroll.
ScrollTrigger.config({ ignoreMobileResize: true });

export default function Home() {
  const router = useRouter();
  const lenisRef = useRef(null);

  const [lenisReady, setLenisReady] = useState(false);

  useLayoutEffect(() => {
    history.scrollRestoration = "manual";
    window.scrollTo(0, 0);

    const onMobile = window.innerWidth < 720;

    /* ── MÓVIL: scroll nativo ────────────────────────────────── */
    if (onMobile) {
      setLenisReady(true);
      gsap.ticker.lagSmoothing(0);
      ScrollTrigger.refresh();
      return () => {
        setLenisReady(false);
        ScrollTrigger.refresh(true);
      };
    }

    /* ── DESKTOP: Lenis + proxy ──────────────────────────────── */
    const lenis = new Lenis();
    lenisRef.current = lenis;
    lenis.scrollTo(0, { immediate: true });

    const scroller = document.documentElement;
    ScrollTrigger.scrollerProxy(scroller, {
      scrollTop(value) {
        if (arguments.length) {
          lenis.scrollTo(value, { immediate: true, force: true });
        }
        return lenis.scroll;
      },
      getBoundingClientRect() {
        return {
          top: 0,
          left: 0,
          width: window.innerWidth,
          height: window.innerHeight,
        };
      },
    });
    ScrollTrigger.defaults({ scroller });
    setLenisReady(true);
    ScrollTrigger.refresh();

    lenis.on("scroll", ScrollTrigger.update);
    const rafCb = (time) => lenis.raf(time * 1000);
    gsap.ticker.add(rafCb);
    gsap.ticker.lagSmoothing(0);

    return () => {
      setLenisReady(false);
      gsap.ticker.remove(rafCb);
      lenis.destroy();
      lenisRef.current = null;
      ScrollTrigger.scrollerProxy(scroller);
      ScrollTrigger.defaults({});
      ScrollTrigger.refresh(true);
    };
  }, []);

  const canRenderSections = lenisReady;

  useEffect(() => {
    const onScrollToY = (event) => {
      const targetY = Number(event?.detail?.y);
      if (!Number.isFinite(targetY)) return;

      if (lenisRef.current) {
        lenisRef.current.scrollTo(targetY, { duration: 1.1 });
        return;
      }

      window.scrollTo({ top: targetY, behavior: "smooth" });
    };

    window.addEventListener("mm-scroll-to", onScrollToY);
    return () => window.removeEventListener("mm-scroll-to", onScrollToY);
  }, []);

  useEffect(() => {
    if (!router.isReady || !canRenderSections) return;

    const focus = Array.isArray(router.query.focus)
      ? router.query.focus[0]
      : router.query.focus;
    if (focus !== "manifesto") return;

    const rafId = requestAnimationFrame(() => {
      window.dispatchEvent(new CustomEvent("mm-nav-manifesto"));
      router.replace("/", undefined, { shallow: true, scroll: false });
    });

    return () => cancelAnimationFrame(rafId);
  }, [router, canRenderSections]);

  return (
    <div>
      <Head>
        <title>MM Discos | Balearic Soundsystem</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {canRenderSections ? (
        <>
          <MMNewestHero2Wrapper />
          <Highlights2Wrapper />
          <AboutFinal2 />
        </>
      ) : null}
    </div>
  );
}
